// AUTH
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN'
export const AUTH_LOG_ERROR = 'AUTH_LOG_ERROR'

// QUESTIONS

export const RETRIEVE_QUESTIONS = 'RETRIEVE_QUESTIONS'

// SETTINGS

export const INIT_SETTINGS = 'INIT_SETTINGS'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_SETTINGS_BY_SETTINGS = 'UPDATE_SETTINGS_BY_SETTINGS'

// SOUND

export const PLAY_SOUND = 'PLAY_SOUND'
export const STOP_SOUND = 'STOP_SOUND'
